outputs:
  count:
    value: ${{ steps.loopcount.outputs.count }}
runs:
  using: "composite"
  steps:
    - id: loopcount
      run: |
          WORD_COUNTER=0
          for i in $(find ./ -type f \( -iname \*.txt -o -iname \*.md \));
          do
            a=($(wc $i))
            lines=${a[0]}
            words=${a[1]}
            chars=${a[2]}
          
            WORD_COUNTER=$(expr $WORD_COUNTER + $words + 1)
            wc -w < $i
          done;
          echo "::set-output name=count::$WORD_COUNTER"
      shell: bash
